
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'EGALE IDENTIFIANT MOINS NOMBRE PLUSexpression : expression PLUS expressionexpression : NOMBREexpression : IDENTIFIANT EGALE NOMBRE'
    
_lr_action_items = {'NOMBRE':([0,4,5,],[2,2,7,]),'IDENTIFIANT':([0,4,],[3,3,]),'$end':([1,2,6,7,],[0,-2,-1,-3,]),'PLUS':([1,2,6,7,],[4,-2,4,-3,]),'EGALE':([3,],[5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,4,],[1,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS expression','expression',3,'p_expression_plus','hy.py',27),
  ('expression -> NOMBRE','expression',1,'p_expression_nombre','hy.py',31),
  ('expression -> IDENTIFIANT EGALE NOMBRE','expression',3,'p_expression_identifiant','hy.py',34),
]
